[vid-tag "com"]
	caption = This photo or video may be downloaded and used freely for non-commercial purposes or by bona fide media services, provided that the photographer and ProbonoPhoto are credited whenever it is used. (https://www.probonophoto.org/Who-We-Are/Bruce-Rafnel). The photographer retains copyright to this image. This is a CC-NC-BY-4.0 license: https://creativecommons.org/licenses/by-nc/4.0/
	copyright = Copyright Bruce Rafnel 2026
	file-pat = %d_%e_%p_%f
	name-long = Bruce Rafnel
	name-short = BAR
	title-pat = %D, %c, %E, by %P.
[vid-tag "testevent"]
	city = Redwood City
	title = This is a test title
	keyword = PBP,Protest
	file-list = MVI_0107.MP4 MVI_0110.MP4 MVI_0746.MP4
